package com.tracy.slark.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tracy.slark.dao.SlarkLog;

import com.tracy.slark.dao.SlarkLogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig slarkLogDaoConfig;

    private final SlarkLogDao slarkLogDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        slarkLogDaoConfig = daoConfigMap.get(SlarkLogDao.class).clone();
        slarkLogDaoConfig.initIdentityScope(type);

        slarkLogDao = new SlarkLogDao(slarkLogDaoConfig, this);

        registerDao(SlarkLog.class, slarkLogDao);
    }

    public void clear() {
        slarkLogDaoConfig.clearIdentityScope();
    }

    public SlarkLogDao getSlarkLogDao() {
        return slarkLogDao;
    }

}
